import os

import glob

# --- ENSEMBLE MODEL FUSION WEIGHTS ---
WEIGHT_MODEL = 0.40
WEIGHT_ARTIFACT = 0.20
WEIGHT_TEMPORAL = 0.15
WEIGHT_METADATA = 0.10
WEIGHT_COMPRESSION = 0.15

# --- DECISION THRESHOLDS (3-tier) ---
# < THRESHOLD_APPROVE  → APPROVED (real)
# THRESHOLD_APPROVE to THRESHOLD_REJECT → UNDER_REVIEW
# >= THRESHOLD_REJECT  → REJECTED (deepfake)
THRESHOLD_APPROVE = 0.58
THRESHOLD_REJECT = 0.72

# --- MULTI-PATCH CONFIG ---
PATCH_COUNT = 10

# --- PERFORMANCE CONFIG ---
MAX_FRAMES_TO_PROCESS = 32
FRAME_SAMPLE_RATE = 1

# --- PATHS ---
MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")
os.makedirs(MODELS_DIR, exist_ok=True)

# Discover all ONNX models in the models directory
AVAILABLE_ONNX_MODELS = sorted(glob.glob(os.path.join(MODELS_DIR, "*.onnx")))

# --- TERTIARY REVIEW ---
SWIN_FAKE_INDEX = int(os.getenv("SWIN_FAKE_INDEX", "1"))
SWIN_HIGH_RISK_THRESHOLD = float(os.getenv("SWIN_HIGH_RISK_THRESHOLD", "0.85"))
SWIN_ELEVATED_RISK_THRESHOLD = float(os.getenv("SWIN_ELEVATED_RISK_THRESHOLD", "0.70"))
