import os

# --- EFFICIENTNET FUSION WEIGHTS ---
WEIGHT_MODEL = 0.40
WEIGHT_ARTIFACT = 0.20
WEIGHT_TEMPORAL = 0.15
WEIGHT_METADATA = 0.10
WEIGHT_COMPRESSION = 0.15

# --- DECISION THRESHOLDS ---
THRESHOLD_REJECT = 0.60
THRESHOLD_UNSAFE = 0.40

# --- PERFORMANCE CONFIG ---
MAX_FRAMES_TO_PROCESS = 32
FRAME_SAMPLE_RATE = 1

# --- PATHS ---
MODEL_PATH = os.path.join(os.path.dirname(__file__), "models", "efficientnet_b0_v1.onnx")
os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
